"""Regression vectors: freeze the semantics of the reference model.

These vectors were generated by scripts/gen_vectors.py from this repository
(no external vectors for DuX exist that agree with the paper).  A failure
here means the cipher's semantics changed; that is only allowed when a
definitional statement of the paper (Wu et al., DCC 2026, 94:140) demands
it, and then the change must be documented in the commit and the vectors
regenerated deliberately.
"""
import glob
import json
import os

import numpy as np
import pytest

from dux import DuX
from dux.params import INSTANCES, WORDS, M0_ROW_65537
from dux.linear import LinearLayer
from dux.field import make_field

VEC_DIR = os.path.join(os.path.dirname(__file__), "vectors")
VEC_FILES = sorted(glob.glob(os.path.join(VEC_DIR, "dux_*.json")))


def load(path):
    with open(path) as fh:
        return json.load(fh)


@pytest.mark.parametrize("path", VEC_FILES, ids=[os.path.basename(p) for p in VEC_FILES])
def test_vector_file_matches_model(path):
    data = load(path)
    inst = data["instance"]
    spec = INSTANCES[inst]
    assert (spec["field"], spec["alpha"], spec["rounds"]) == \
           (data["field"], data["alpha"], data["rounds"])
    c = DuX(inst)
    assert len(data["vectors"]) >= 5
    for v in data["vectors"]:
        K, P, C = tuple(v["K"]), tuple(v["P"]), tuple(v["C"])
        assert len(K) == len(P) == len(C) == WORDS
        rks = c.key_schedule(K)
        assert [list(rk) for rk in rks] == v["round_keys"]
        assert c.encrypt(P, rks) == C
        assert c.decrypt(C, rks) == P
        # encryption intermediate states
        x = c.ARK(P, rks[0])
        assert list(x) == v["enc_states"][0]
        for i in range(1, c.r):
            x = c.ARK(c.lin.LM(c.SL(x), rks[i]), rks[i])
            assert list(x) == v["enc_states"][i]
        assert list(c.ARK(c.SL(x), rks[c.r])) == v["enc_states"][c.r] == list(C)
        # decryption layer states (used by every zero-sum experiment)
        dec = c.decrypt_layers(C, rks, c.r, yield_all=True)
        assert [list(s) for s in dec] == v["dec_layer_states"]


@pytest.mark.parametrize("path", VEC_FILES, ids=[os.path.basename(p) for p in VEC_FILES])
def test_vectors_match_vectorised_path(path):
    """The numpy path must reproduce the scalar vectors bit for bit."""
    data = load(path)
    c = DuX(data["instance"])
    vs = data["vectors"]
    rks = c.key_schedule(tuple(vs[0]["K"]))
    same_key = [v for v in vs if v["K"] == vs[0]["K"]] or [vs[0]]
    Ps = [v["P"] for v in same_key]
    Pv = tuple(np.array([p[i] for p in Ps], dtype=np.int64) for i in range(WORDS))
    Cv = c.encrypt(Pv, rks, vec=True)
    for k, v in enumerate(same_key):
        assert [int(w[k]) for w in Cv] == v["C"]


def test_paper_Fp_matrix_fractions_reduce_to_printed_row():
    """Paper Sect. 3.2.2 gives M0 both as fractions b/1105 over F_p and as
    explicit integers for p = 65537; check the two agree, and that the
    generic circulant inverse used by dux/linear.py equals them."""
    p = 65537
    num = [-359, -209, -174, -129, -229, 116, 86, 521,
           291, 311, 21, -194, 161, -14, -239, 261]
    inv1105 = pow(1105, p - 2, p)
    row = tuple((n * inv1105) % p for n in num)
    assert row == M0_ROW_65537
    lin = LinearLayer(make_field("65537"))
    assert lin._rows[0] == row
    # M1 is M0 shifted by one 4-word sub-block (paper Sect. 3.2.2)
    assert lin._rows[1] == tuple(row[(k + 4) % 16] for k in range(16))
